### ISSUE TITLE
Core Sim Performance

### ISSUE THREAD

**Issue by prchall123** [cmu-argus-2/GNC-Simulation#12]

**Comment by nlitz88** [comment]
Notes on proposed simulation rewrite: https://www.notion.so/Meeting-Notes-30-September-11148018d82a80c89c58ea77b613a8e9?pvs=4#11148018d82a80a98f6ef4bccbfd2fe2

While maybe not strictly necessary, it might be nice to break this refactor into concrete tasks / items, even if @2shaar2059 ends up blasting through it lol. Could help for visibility / tracking the progress of the updates being made--as each addition could have its own feature branch that we review before merging, etc.

**Comment by kmkar31** [comment]
Closed by #24
